### ISSUE TITLE
INFOGRAFIA_MAVIEL_MARTINEZ_CHOLULA

### ISSUE THREAD

**Issue by MAB288** [SistemasTecTlaxiaco/actividad-1-infografia-MAB288#2]
[iINFOGRAFIA DE FASES DE DESARROLLO DE SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-MAB288/files/12491491/iINFOGRAFIA.DE.FASES.DE.DESARROLLO.DE.SOFTWARE.pdf)

**Comment by ToniDepp** [comment]
Redacción y ortografía: Detalles muy llamativos 2.5 puntos de 3 puntos
Exposición de ideas centrales: Lo indispensable 3 puntos de 3 puntos
Organización de la información: Se pudo haber hecho mejor 2 puntos de 3 puntos
Uso de imágenes y colores: Resoluciones un poco bajas, pero se entiende el mensaje 2.5 puntos de 3 puntos
Presentación visual: Buen diseño 3 puntos de 3 puntos
Referencias: No se menciona ni uno 0 puntos de 2 puntos 
Presentación: 3 puntos de 3 puntos
Calificación: 16/ 20
Calificado por: Eduardo Tomas

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
